spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slooze   # your db name
    driver-class-name: org.postgresql.Driver
    username: postgres     # your postgres username
    password: postgres # your postgres password

  jpa:
    hibernate:
      ddl-auto: update     # keep update for dev (creates tables automatically)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080
